# # image_size: 32
# num_clients: 40
# global_epochs: 5
# local_epochs: 2
# imbalance_ratio: 0.5
# dataset_name: "mnist" #mnist #cifar10 #ham10000 is not compitable yet
# train_sample_fraction: 1
# test_sample_fraction: 1
# min_samples_per_client: 1
# frac: 0.5
# batch_size: 128
# model_name: "resnet18" #resnet18 #cnn #vgg
# num_clusters: 3
# # num_classes: 10

# dataset_name: "mnist"  # or "mnist" "cifar10"
# model_name: "ResNet18"
# num_clients: 10
# global_epochs: 2
# local_epochs: 1
# batch_size: 128
# frac: 0.5
# imbalance_ratio: 0.5
# train_sample_fraction: 0.2
# test_sample_fraction: 0.2
# min_samples_per_client: 5
# num_clusters: 3

# #initialization
# learning_rate: 0.001 # Initial learning rate for all clients

# # --- NEW SECTION FOR HPO STRATEGY ---
# hpo_strategy:
#   # Method can be: agent, fixed, random_search, successive_halving, bo, etc.
#   method: agent 
  
 
#   # For the 'fixed' strategy, you could specify the HPs.
#   fixed_hps:
#     learning_rate: 0.01
#     weight_decay: 5.0e-5
#     optimizer: 'AdamW'
#     mu: 0.01

# Model and Dataset Configuration
model_name: charlstm  #ResNet18 #bert #charlstm
dataset_name: shakespeare #cifar10 #mnist #femnist #shakespeare
imbalance_ratio: 0.5
train_sample_fraction: 1.0
test_sample_fraction: 1.0
min_samples_per_client: 30
num_clusters: 3
# num_classes: 10
# in_channels: 1

# Federated Learning Configuration
num_clients: 1129  #for shakespear 1129
global_epochs: 50
frac: 0.01  # Fraction of clients participating in each round
fl_mode: centralized #splitfed #centralized

# --- REMOVED ---
# local_epochs and batch_size are now optimized by the agent.

# NEW: Training Control Parameters
training_params:
  patience: 15
  min_delta: 0.01

# HPO Agent Configuration
hpo_strategy:
  method: agent # Can be agent, random_search, sha, bo, fixed
  hpo_checkpoint_path: agent/client_hpo_states.yaml
  history_window: 5 
  # Stop optimizing a client if its accuracy hasn't improved for this many rounds.
  # hpo_patience: 3

  # Example config for SHA strategy (only used if method is 'sha')
  sha_config:
    population_size: 27
    elimination_rate: 3