# # image_size: 32
# num_clients: 40
# global_epochs: 5
# local_epochs: 2
# imbalance_ratio: 0.5
# dataset_name: "mnist" #mnist #cifar10 #ham10000 is not compitable yet
# train_sample_fraction: 1
# test_sample_fraction: 1
# min_samples_per_client: 1
# frac: 0.5
# batch_size: 128
# model_name: "resnet18" #resnet18 #cnn #vgg
# num_clusters: 3
# # num_classes: 10

dataset_name: "mnist"  # or "mnist"
model_name: "ResNet18"
num_clients: 10
global_epochs: 5
local_epochs: 2
batch_size: 128
frac: 0.5
imbalance_ratio: 0.5
train_sample_fraction: 1.0
test_sample_fraction: 1.0
min_samples_per_client: 5
num_clusters: 3


#initialization
learning_rate: 0.001 # Initial learning rate for all clients
